### PR TITLE
Preventing Runtime Error caused by "Event loop is closed"

### PR DESCRIPTION
**Pull request by sturmianseq**
This PR aims to improve test reliability by initializing `loop` before executing `asyncio.get_event_loop()` by calling method `asyncio.set_event_loop` and `asyncio.new_event_loop` in order to prevent Runtime Error caused by "Event loop is closed".

```
test_aio.py:49 (test_aio_future)
Traceback (most recent call last):
  File ".../test_aio.py", line 73, in test_aio_future
    asyncio.Task(write(sock2))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### CODE REVIEW

**Comment by Nikratio** [comment]
Could you give some more information about when this problem is currently being hit? It seems the tests run just fine as-is, at least in the CI and for me. What do I have to do to reproduce the problem?

**Comment by sturmianseq** [comment]
Thanks for your comment! The test can fail by running the following commands:

```python
pip3 install pytest-repeat
python3 -m pytest --count=2 test/test_aio.py::test_aio_future
```

It may be better to clean state pollutions so that some other tests won't fail in the future due to the shared state pollution.

**Comment by Nikratio** [comment]
I've added this to the CI test runner (https://app.travis-ci.com/github/python-dugong/python-dugong/builds/236057274). Could you please re-base and so that we can confirm that the pull request indeed fixes the issue?

**Comment by sturmianseq** [comment]
Thanks for following up. This branch has been rebased to the latest commit in `master`, and I've run Travis CI on this branch: https://app.travis-ci.com/github/sturmianseq/python-dugong/jobs/533601211, and https://app.travis-ci.com/github/sturmianseq/python-dugong/jobs/533601212. I don't know why it fails with `Python: nightly` while the log does not show any failure.

**Pull request merged**
